// domain/entities/facility_tiers_data.dart
// 12 Tesis × 5 Seviye özel isimlendirmeleri, stat bonusları ve görsel detayları.

import 'facility.dart';

class FacilityTierInfo {
  final int tier;
  final String name;
  final String subtitle;
  final String description;
  final String perkTitle;
  final String perkValue;
  final List<String> highlights;

  const FacilityTierInfo({
    required this.tier,
    required this.name,
    required this.subtitle,
    required this.description,
    required this.perkTitle,
    required this.perkValue,
    required this.highlights,
  });
}

class FacilityTiersData {
  static const Map<FacilityType, List<FacilityTierInfo>> tiers = {
    FacilityType.stadium: [
      FacilityTierInfo(
        tier: 1,
        name: 'Toprak Mahalle Sahası',
        subtitle: 'Kapasite: 2.500 Seyirci',
        description: 'Ahşap tribünler, tel örgüler ve kireçli çizgilerle mütevazı başlangıç.',
        perkTitle: 'Bilet Geliri Çarpanı',
        perkValue: '+%10',
        highlights: ['2.500 Kapasite', 'Temel bilet satışı', 'Yerel taraftar desteği'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'İlçe Belediye Stadı',
        subtitle: 'Kapasite: 7.500 Seyirci',
        description: 'Betonarme tribünler, aydınlatma direkleri ve kapalı protokol alanı.',
        perkTitle: 'Bilet Geliri Çarpanı',
        perkValue: '+%20',
        highlights: ['7.500 Kapasite', 'Gece maçları aydınlatması', 'Kombine biletleme'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Bölgesel Şehir Arenası',
        subtitle: 'Kapasite: 18.000 Seyirci',
        description: 'Modern ses sistemi, genişletilmiş localar ve akustik çatı kaplaması.',
        perkTitle: 'Bilet Geliri Çarpanı',
        perkValue: '+%35',
        highlights: ['18.000 Kapasite', 'Akustik ev sahibi baskısı', 'Kurumsal loca satışları'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'Ulusal Futbol Mabedi',
        subtitle: 'Kapasite: 36.000 Seyirci',
        description: 'Çift katlı tribünler, LED paneller ve uluslararası turnuva standartları.',
        perkTitle: 'Bilet Geliri Çarpanı',
        perkValue: '+%55',
        highlights: ['36.000 Kapasite', 'Kıta turnuvası ev sahipliği', 'Yüksek bilet talebi'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Megastadı & Kompleks',
        subtitle: 'Kapasite: 62.000 Seyirci',
        description: 'Açılır-kapanır çatı, 360° dev skorboard ve lüks ticari alanlar.',
        perkTitle: 'Bilet Geliri Çarpanı',
        perkValue: '+%80',
        highlights: ['62.000 Kapasite', 'Maksimum bilet & kombine geliri', 'Yenilmez ev sahibi aurası'],
      ),
    ],

    FacilityType.trainingGround: [
      FacilityTierInfo(
        tier: 1,
        name: 'Çamurlu Antrenman Düzlüğü',
        subtitle: 'Temel Kondisyon',
        description: 'Basit kukalar ve ağırlık çantalarıyla yapılan temel çalışmalar.',
        perkTitle: 'Haftalık Oyuncu Gelişimi',
        perkValue: '+%12 Gelişim',
        highlights: ['Temel pas drilleri', 'Fiziksel kondisyon', 'Genel antrenman'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Standart Çim Saha & Kondisyon Salonu',
        subtitle: 'Mekanik Gelişim',
        description: 'Düzenli çim zemin, kapalı fitness aletleri ve taktik tahtası.',
        perkTitle: 'Haftalık Oyuncu Gelişimi',
        perkValue: '+%24 Gelişim',
        highlights: ['Direnç antrenmanları', 'Hız ve dayanıklılık artışı', 'Pozisyonel taktikler'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Modern Performans Merkezi',
        subtitle: 'Sensörlü Antrenman',
        description: 'GPS takip yelekleri, yapay zemin şut duvarı ve video odası.',
        perkTitle: 'Haftalık Oyuncu Gelişimi',
        perkValue: '+%38 Gelişim',
        highlights: ['Bireysel oyuncu gelişimi', 'Hızlı OVR artışı', 'Taktik ezberleme'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'Yüksek İrtifa & Aerobik Üssü',
        subtitle: 'Elit Dayanıklılık',
        description: 'Oksijen çadırları, kum havuzları ve yüksek tempolu simülatörler.',
        perkTitle: 'Haftalık Oyuncu Gelişimi',
        perkValue: '+%55 Gelişim',
        highlights: ['Maksimum kondisyon tutma', 'Antrenman sakatlığı koruması', 'Duran top uzmanlığı'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Biyomekanik Kampüsü',
        subtitle: 'Ultra-Gelişim Kompleksi',
        description: 'Yapay zeka analizli hız tünelleri ve nöral refleks geliştirme makineleri.',
        perkTitle: 'Haftalık Oyuncu Gelişimi',
        perkValue: '+%75 Gelişim',
        highlights: ['Oyuncular hızla potansiyeline ulaşır', 'Özel yetenek geliştirme', 'Yıldız oyuncu üretimi'],
      ),
    ],

    FacilityType.youthAcademy: [
      FacilityTierInfo(
        tier: 1,
        name: 'Mahalle Seçmeleri & Gençlik Çadırı',
        subtitle: 'Amatör Keşif',
        description: 'Sokak aralarından ve okul turnuvalarından toplanan genç yetenekler.',
        perkTitle: 'Genç Oyuncu Potansiyeli',
        perkValue: 'Maks 65-72 POT',
        highlights: ['Yılda 1 genç alımı', 'Düşük maliyetli sözleşmeler', 'Yerel yetenekler'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Gelişim Yurdu & Amatör Akademi',
        subtitle: 'Düzenli Altyapı',
        description: 'Gençler için yatakhane, temel antrenörler ve haftalık altyapı ligi.',
        perkTitle: 'Genç Oyuncu Potansiyeli',
        perkValue: 'Maks 70-78 POT',
        highlights: ['Gelişmiş teknik temel', 'Yüksek disiplin', 'Düzenli potansiyel artışı'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Bölgesel Futbol Enstitüsü',
        subtitle: 'Bölgesel Cazibe Merkezi',
        description: 'Tüm bölgeden seçilen genç yetenekler ve uzman altyapı koçları.',
        perkTitle: 'Genç Oyuncu Potansiyeli',
        perkValue: 'Maks 78-85 POT',
        highlights: ['Yüksek potansiyelli gençler', 'Doğal liderlik gelişimi', 'Erken A Takım uyumu'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'Elit Yıldız Geliştirme Kompleksi',
        subtitle: 'Milli Takım Tedarikçisi',
        description: 'Kişiselleştirilmiş gelişim programları ve uluslararası gençlik kampları.',
        perkTitle: 'Genç Oyuncu Potansiyeli',
        perkValue: 'Maks 84-91 POT',
        highlights: ['Geleceğin yıldızları', 'Yüksek piyasa değeri', 'Çift mevki yeteneği'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Yıldız Fabrikası',
        subtitle: 'Dünya Çapında Efsaneler',
        description: 'Dünyanın dört bir yanından yetenek çeken efsanevi La Masia tarzı akademi.',
        perkTitle: 'Genç Oyuncu Potansiyeli',
        perkValue: 'Maks 90-97 POT (Wonderkid)',
        highlights: ['Kesin Wonderkid (%4 şans yerine garanti)', 'Dünya yıldızı adayları', 'Dev bonservis kazançları'],
      ),
    ],

    FacilityType.medicalCenter: [
      FacilityTierInfo(
        tier: 1,
        name: 'İlk Yardım Kabini & Sargı İstasyonu',
        subtitle: 'Temel Müdahale',
        description: 'Buz torbaları, bandajlar ve temel ağrı kesicilerle ilk müdahale.',
        perkTitle: 'Sakatlık Koruma & İyileşme',
        perkValue: '-%8 Risk / -%10 Süre',
        highlights: ['Hafif sakatlık tedavisi', 'Temel saha içi müdahale', 'Düşük masraf'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Kulüp Kliniği & Masaj Ünitesi',
        subtitle: 'Fizyoterapi Odası',
        description: 'Uzman masörler, ultrason tedavi cihazları ve kas gevşetici havuzlar.',
        perkTitle: 'Sakatlık Koruma & İyileşme',
        perkValue: '-%16 Risk / -%20 Süre',
        highlights: ['Kas sakatlıklarını önleme', 'Maç sonrası hızlı toparlanma', 'Fitness koruma'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Ortopedi & Spor Hekimliği Merkezi',
        subtitle: 'İleri Teşhis',
        description: 'Dijital MR cihazı, eklem tedavisi uzmanları ve erken uyarı testleri.',
        perkTitle: 'Sakatlık Koruma & İyileşme',
        perkValue: '-%25 Risk / -%32 Süre',
        highlights: ['Bağ sakatlığı süresini yarıya indirme', 'Kronik sakatlık kontrolü', 'Yüksek kondisyon'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'Kriyoterapi & Biyofizik Kliniği',
        subtitle: 'Ultra-Soğuk Tedavi',
        description: '-110°C kriyoterapi kabinleri, hiperbarik oksijen odaları.',
        perkTitle: 'Sakatlık Koruma & İyileşme',
        perkValue: '-%35 Risk / -%45 Süre',
        highlights: ['24 saatte hızlı dinlenme', 'Ağır sakatlıkları 1 haftada çözme', 'Sıfır nüksetme'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Rejenerasyon Hastanesi',
        subtitle: 'Yenilmez Bedenler',
        description: 'Kök hücre terapisi, genetik rejenerasyon ve yapay zeka destekli cerrahi üs.',
        perkTitle: 'Sakatlık Koruma & İyileşme',
        perkValue: '-%50 Risk / -%65 Süre',
        highlights: ['Sakatlık neredeyse imkansızlaşır', '3 günde tam iyileşme', 'Kariyer uzatma'],
      ),
    ],

    FacilityType.scoutCenter: [
      FacilityTierInfo(
        tier: 1,
        name: 'Gözlemci Not Defteri & Amatör Ağ',
        subtitle: 'Temel Gözlem',
        description: 'Yerel maçlara giden gönüllü gözlemciler ve el yazısı raporlar.',
        perkTitle: 'Scout Doğruluğu & Aday Sayısı',
        perkValue: '+2 Oyuncu / ±6 Hata Payı',
        highlights: ['Pazarda ek oyuncu keşfi', 'Temel OVR tahmini', 'Yerel lig oyuncuları'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Bölgesel İstihbarat Bürosu',
        subtitle: 'Veri Arşivi',
        description: 'Bölge kulüplerinin maç kayıtları ve yetenek listeleme sistemi.',
        perkTitle: 'Scout Doğruluğu & Aday Sayısı',
        perkValue: '+4 Oyuncu / ±4 Hata Payı',
        highlights: ['Gelişmiş potansiyel aralığı', 'Sözleşme sonu yaklaşanları bulma', 'Gizli maddeleri görme'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Ulusal Veri Tabanı & Video Üssü',
        subtitle: 'Dijital Tarama',
        description: 'Tüm lig maçlarının anlık video akışı ve istatistik filtreleme motoru.',
        perkTitle: 'Scout Doğruluğu & Aday Sayısı',
        perkValue: '+6 Oyuncu / ±2 Hata Payı',
        highlights: ['Nokta atışı transfer tavsiyeleri', 'Ucuz kelepir yetenekler', 'Kişilik tipi analizi'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'Uluslararası Yetenek Radarı',
        subtitle: 'Kıta Çapında Ağ',
        description: 'Güney Amerika, Balkanlar ve Afrika bağlantılı profesyonel temsilciler.',
        perkTitle: 'Scout Doğruluğu & Aday Sayısı',
        perkValue: '+8 Oyuncu / ±1 Hata Payı',
        highlights: ['Yurtdışı wonderkid keşfi', 'Bonservissiz yıldız tespiti', 'Karşı kulüp sabır analizi'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Global Scout & AI Ağı',
        subtitle: 'Kusursuz Görüş',
        description: 'Dünya üzerindeki her futbolcuyu 24 saat izleyen küresel uydu & AI ağı.',
        perkTitle: 'Scout Doğruluğu & Aday Sayısı',
        perkValue: '+10 Oyuncu / %100 Kesinlik',
        highlights: ['Sıfır hata payı', 'Tüm gizli nitelikleri görme', 'Geleceğin Ballon d\'Or adayları'],
      ),
    ],

    FacilityType.clubMuseum: [
      FacilityTierInfo(
        tier: 1,
        name: 'Kupa Dolabı & Fotoğraf Köşesi',
        subtitle: 'İlk Zaferler',
        description: 'Kulüp binası girişinde kazanılan ilk madalyalar ve eski fotoğraflar.',
        perkTitle: 'Taraftar & İtibar Bonusu',
        perkValue: '+%5 Taraftar Bağlılığı',
        highlights: ['Haftalık küçük bilet primi', 'Kulüp tarihi başlangıcı', 'Nostalji sergisi'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Tarih ve Zafer Odası',
        subtitle: 'Gelenek Oluşumu',
        description: 'Eski formaların sergilendiği ve efsane kaptanların anıldığı özel oda.',
        perkTitle: 'Taraftar & İtibar Bonusu',
        perkValue: '+%10 Taraftar Bağlılığı',
        highlights: ['Müze giriş bilet geliri', 'Kriz anlarında yönetim toleransı', 'Efsane oyuncu kaydı'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Şampiyonluklar Ziyaretçi Merkezi',
        subtitle: 'Turistik Cazibe',
        description: 'Hafta sonu taraftar turları, kupa replikaları ve belgesel gösterim salonu.',
        perkTitle: 'Taraftar & İtibar Bonusu',
        perkValue: '+%18 Taraftar Bağlılığı',
        highlights: ['Yüksek müze geliri', 'Şehir genelinde sempati', 'Oyuncu transfer çekiciliği'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'İnteraktif VR & Miras Pavilyonu',
        subtitle: 'Geleceğin Müzesi',
        description: 'Tarihi anların VR gözlüklerle izlendiği yüksek teknolojili sergi alanı.',
        perkTitle: 'Taraftar & İtibar Bonusu',
        perkValue: '+%28 Taraftar Bağlılığı',
        highlights: ['Uluslararası turist ilgisi', 'Devasa marka değeri', 'Sponsorluk teklif çarpanı'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Efsaneler Mabedi',
        subtitle: 'Ölümsüz Tarih Sarayı',
        description: 'Dünya futbolunun en görkemli başarılarının altın heykellerle taçlandırıldığı mabet.',
        perkTitle: 'Taraftar & İtibar Bonusu',
        perkValue: '+%40 Taraftar / +%25 Sponsorluk',
        highlights: ['Dünya çapında saygınlık', 'Asla düşmeyen yönetim güveni', 'Kalıcı efsane statüsü'],
      ),
    ],

    FacilityType.fanShop: [
      FacilityTierInfo(
        tier: 1,
        name: 'Seyyar Forma Tezgahı',
        subtitle: 'Maç Günü Satış',
        description: 'Stadyum çevresinde atkı ve temel forma satan mobil araç.',
        perkTitle: 'Haftalık Ürün Satış Geliri',
        perkValue: '+₣1.200 / Hafta',
        highlights: ['Ek pasif gelir', 'Maç günü forma satışı', 'Temel kulüp ürünleri'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Stadyum Önü Resmi Büfesi',
        subtitle: 'Kalıcı Mağaza',
        description: 'Resmi logolu ürünler, şapkalar ve orijinal sezon formaları.',
        perkTitle: 'Haftalık Ürün Satış Geliri',
        perkValue: '+₣2.800 / Hafta',
        highlights: ['Sürekli açık mağaza', 'Sezonluk forma lansmanları', 'Düzenli nakit akışı'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Resmi Kulüp Mağazası (Store)',
        subtitle: 'Kapsamlı Koleksiyon',
        description: 'Geniş ürün yelpazesi, çocuk reyonu ve imzalı oyuncu aksesuarları.',
        perkTitle: 'Haftalık Ürün Satış Geliri',
        perkValue: '+₣5.200 / Hafta',
        highlights: ['Yüksek kar marjı', 'Yeni transfer forma patlaması', 'Şehir içi popülerlik'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'Şehir Merkezi Mega Fan Store',
        subtitle: 'Prestij Mağazası',
        description: 'Alışveriş merkezlerinde ve işlek caddelerde çok katlı konsept mağazalar.',
        perkTitle: 'Haftalık Ürün Satış Geliri',
        perkValue: '+₣9.000 / Hafta',
        highlights: ['Şehir genelinde mağaza zinciri', 'Uluslararası kargo satışı', 'Büyük ticari güç'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Global Flagship Store',
        subtitle: 'Küresel Moda & Ticaret',
        description: 'Dünya metropollerinde bulunan, moda markalarıyla ortak çalışan lüks mağazalar.',
        perkTitle: 'Haftalık Ürün Satış Geliri',
        perkValue: '+₣15.000 / Hafta',
        highlights: ['Dünya çapında forma rekorları', 'Devasa haftalık pasif nakit', 'Global marka gücü'],
      ),
    ],

    FacilityType.analyticsDept: [
      FacilityTierInfo(
        tier: 1,
        name: 'Kara Tahta & İstatistik Defteri',
        subtitle: 'Temel Taktik',
        description: 'Yardımcı antrenörün elle tuttuğu şut ve korner istatistikleri.',
        perkTitle: 'Maç Taktik İsabeti',
        perkValue: '+%5 Taktik Uyum',
        highlights: ['Basit rakip diziliş bilgisi', 'Devre arası küçük ipucu', 'Temel xG hesabı'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Video Kaset & Maç Çözümleme Odası',
        subtitle: 'Görsel Analiz',
        description: 'Rakip forvetlerin alışkanlıklarını gösteren video klipleri ve şut haritaları.',
        perkTitle: 'Maç Taktik İsabeti',
        perkValue: '+%10 Taktik Uyum',
        highlights: ['Rakibin tehlikeli oyuncusunu kilitleme', 'Duran top savunma planı', 'Taktik kararlarda +%10 başarı'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Dijital GPS & Performans Laboratuvarı',
        subtitle: 'Metrik Odaklı',
        description: 'Koşu mesafeleri, pres haritaları ve gerçek zamanlı yorgunluk takibi.',
        perkTitle: 'Maç Taktik İsabeti',
        perkValue: '+%18 Taktik Uyum',
        highlights: ['Canlı karar anlarında ekstra seçenek', 'Zayıf kanat tespiti', 'Doğru oyuncu değişikliği tavsiyesi'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'İleri Düzey xG & Sentetik Analiz Üssü',
        subtitle: 'Büyük Veri',
        description: 'Milyonlarca simülasyon çalıştıran yapay zeka maç tahmin motoru.',
        perkTitle: 'Maç Taktik İsabeti',
        perkValue: '+%28 Taktik Uyum',
        highlights: ['Rakibin oyun planını %100 çözme', 'Maç içi kritik an bonusu', 'Garantili taktik üstünlük'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Kuantum Taktik Simülasyonu',
        subtitle: 'Geleceği Gören Sistem',
        description: 'Maçın her dakikasını kuantum olasılık algoritmalarıyla önceden çözen üs.',
        perkTitle: 'Maç Taktik İsabeti',
        perkValue: '+%40 Taktik Uyum / +%15 Gol Şansı',
        highlights: ['Rakip taktiğini felç etme', 'Kusursuz karşı taktik', 'Yenilmezlik serisi desteği'],
      ),
    ],

    FacilityType.pitchMaintenance: [
      FacilityTierInfo(
        tier: 1,
        name: 'El Biçme Makinesi & Kireç Çizgileri',
        subtitle: 'Klasik Zemin',
        description: 'Maç sabahı çimleri biçen ve çizgileri çeken fedakar emektar ekip.',
        perkTitle: 'Saha Avantajı & Zemin Kalitesi',
        perkValue: '+%5 Saha Avantajı',
        highlights: ['Temel zemin bakımı', 'Top yuvarlanma standardı', 'Düşük masraf'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Drenaj Sistemi & Motorlu Bakım',
        subtitle: 'Yağmur Koruması',
        description: 'Yağmurlu havalarda su birikintilerini önleyen yer altı drenaj boruları.',
        perkTitle: 'Saha Avantajı & Zemin Kalitesi',
        perkValue: '+%10 Saha Avantajı',
        highlights: ['Yağmurda pas hatasını azaltma', 'Sert zemin sakatlığını önleme', 'Hızlı oyun akışı'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Hibrit Zemin & Akıllı Sulama',
        subtitle: 'Dayanıklı Çim',
        description: 'Doğal çim lifleriyle dokunmuş sentetik güçlendirmeli modern zemin.',
        perkTitle: 'Saha Avantajı & Zemin Kalitesi',
        perkValue: '+%18 Saha Avantajı',
        highlights: ['Kusursuz pas trafiği', 'Ev sahibi teknik üstünlüğü', 'Sıfır zemin çökmesi'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'Alttan Isıtmalı & Güneş Panelli Saha',
        subtitle: 'Dört Mevsim Çim',
        description: 'Kışın donmayı engelleyen sıcak su boruları ve fotosentez ışık kuleleri.',
        perkTitle: 'Saha Avantajı & Zemin Kalitesi',
        perkValue: '+%28 Saha Avantajı',
        highlights: ['Karda bile halı gibi zemin', 'Rakipleri fiziksel olarak yorma', 'Ekstra ev sahibi baskısı'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Kusursuz Hibrit Çim Mühendisliği',
        subtitle: 'Futbolun Halısı',
        description: 'Mikro iklim kontrollü, nanoteknolojik kök beslemeli dünyanın en iyi zemini.',
        perkTitle: 'Saha Avantajı & Zemin Kalitesi',
        perkValue: '+%40 Saha Avantajı',
        highlights: ['Deplasman takımları tamamen yabancılık çeker', 'Maksimum hız ve teknik', 'Sıfır sakatlık riski'],
      ),
    ],

    FacilityType.pressRoom: [
      FacilityTierInfo(
        tier: 1,
        name: 'Koridorda Ayaküstü Röportaj Köşesi',
        subtitle: 'Mütevazı Mikrofon',
        description: 'Soyunma odası çıkışında dikilen kulüp flaması önünde kısa demeçler.',
        perkTitle: 'Basın Baskısı & Yönetim Koruması',
        perkValue: '-%5 Basın Baskısı',
        highlights: ['Basit maç sonu demeci', 'Yönetimle temel diyalog', 'Yerel gazete haberleri'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Ses Düzenli Küçük Brifing Odası',
        subtitle: 'Düzenli Basın',
        description: '15 sandalyeli, sponsor panolu ve ses kayıt cihazlı düzenli oda.',
        perkTitle: 'Basın Baskısı & Yönetim Koruması',
        perkValue: '-%12 Basın Baskısı',
        highlights: ['Kriz anlarında panik kontrolü', 'Yalan haberleri yalanlama', 'Yönetim güveni koruma'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Canlı Yayın Altyapılı Medya Salonu',
        subtitle: 'Görsel Güç',
        description: 'Ulusal televizyonların canlı bağlandığı, simultane çevirili modern salon.',
        perkTitle: 'Basın Baskısı & Yönetim Koruması',
        perkValue: '-%20 Basın Baskısı',
        highlights: ['Sahne İnsanı yeteneklerine bonus', 'Hakem hatalarını gündem yapma', 'Taraftar algı yönetimi'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: '4K Konferans & Uluslararası Medya Üssü',
        subtitle: 'Global Görünürlük',
        description: 'Yabancı basının ağırlandığı, ses yalıtımlı profesyonel TV stüdyosu.',
        perkTitle: 'Basın Baskısı & Yönetim Koruması',
        perkValue: '-%30 Basın Baskısı',
        highlights: ['Kötü mağlubiyetlerde bile sıfır güven kaybı', 'Global sponsor çekme', 'Menajer karizması'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Global Medya & Kongre Sarayı',
        subtitle: 'Medya İmparatorluğu',
        description: 'Kendi dijital TV kanalını ve küresel basın ajansını barındıran devasa merkez.',
        perkTitle: 'Basın Baskısı & Yönetim Koruması',
        perkValue: '-%45 Basın Baskısı / +%20 İtibar',
        highlights: ['Basın tamamen kulübün arkasında durur', 'Kriz anı yok edilir', 'Dünya çapında popülerlik'],
      ),
    ],

    FacilityType.nutritionCenter: [
      FacilityTierInfo(
        tier: 1,
        name: 'Temel Yemekhane & Su Sebil İstasyonu',
        subtitle: 'Basit Beslenme',
        description: 'Standart karbonhidrat menüsü ve vitamin takviyeleri.',
        perkTitle: 'Yorgunluk Azaltma & Enerji',
        perkValue: '+%5 Maç Sonu Enerji',
        highlights: ['Temel toparlanma', 'Açlık ve yorgunluk önleme', 'Mütevazı maliyet'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Diyetisyen & Protein Hazırlama Barı',
        subtitle: 'Özel Diyet',
        description: 'Oyuncu bazlı kalori planları, taze meyve suları ve protein shakeler.',
        perkTitle: 'Yorgunluk Azaltma & Enerji',
        perkValue: '+%12 Maç Sonu Enerji',
        highlights: ['Kas kramplarını önleme', '70. dakikadan sonra diri kalma', 'Daha hızlı fitness artışı'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Profesyonel Sporcu Mutfağı & Kalori Labı',
        subtitle: 'Performans Şefleri',
        description: 'Özel sporcu şefleri, kişiye özel kan tahliline göre hazırlanan süper gıdalar.',
        perkTitle: 'Yorgunluk Azaltma & Enerji',
        perkValue: '+%20 Maç Sonu Enerji',
        highlights: ['Haftada 2 maç temposuna dayanıklılık', '90+ dakikalarda kondisyon üstünlüğü', 'Yüksek moral'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'Moleküler Beslenme & Biyo-Yakıt Üssü',
        subtitle: 'Hücresel Güç',
        description: 'Hücre yenileyici antioksidanlar, hidrasyon sensörleri ve özel elektrolitler.',
        perkTitle: 'Yorgunluk Azaltma & Enerji',
        perkValue: '+%30 Maç Sonu Enerji',
        highlights: ['Yorgunluk kaynaklı sakatlıkları sıfırlama', 'Sürekli 90+ fitness', 'Uzatma dakikalarında patlama'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Hücresel Restorasyon Merkezi',
        subtitle: 'Tükenmeyen Enerji',
        description: 'DNA tabanlı biyo-beslenme, anlık laktat temizleme ve sonsuz enerji formülü.',
        perkTitle: 'Yorgunluk Azaltma & Enerji',
        perkValue: '+%45 Maç Sonu Enerji',
        highlights: ['Oyuncular asla yorulmaz', 'Her maç %100 form', 'Kadro rotasyonu gereksinimi azalır'],
      ),
    ],

    FacilityType.vipLounge: [
      FacilityTierInfo(
        tier: 1,
        name: 'Şeref Tribünü Ahşap Koltukları',
        subtitle: 'Protokol Alanı',
        description: 'Yerel iş insanları ve yöneticiler için ayrılmış minderli oturma alanı.',
        perkTitle: 'VIP Geliri & Sponsorluk Çarpanı',
        perkValue: '+₣1.500 / Hafta',
        highlights: ['Temel protokol geliri', 'Yerel destekçiler', 'Ek bütçe katkısı'],
      ),
      FacilityTierInfo(
        tier: 2,
        name: 'Kapalı Camlı Protokol Locası',
        subtitle: 'Özel Hizmet',
        description: 'Isıtmalı cam localar, çay-kahve ikramı ve özel stadyum girişi.',
        perkTitle: 'VIP Geliri & Sponsorluk Çarpanı',
        perkValue: '+₣3.500 / Hafta',
        highlights: ['Kurumsal kombine satışları', 'İş dünyası bağlantıları', 'Sponsor memnuniyeti'],
      ),
      FacilityTierInfo(
        tier: 3,
        name: 'Executive Garsonlu İş Locaları',
        subtitle: 'Lüks Hizmet',
        description: 'Restoran kalitesinde yemek servisi, TV ekranları ve özel otopark.',
        perkTitle: 'VIP Geliri & Sponsorluk Çarpanı',
        perkValue: '+₣7.000 / Hafta',
        highlights: ['Büyük holding sponsorlukları', 'Koltuk başına rekor gelir', 'Yüksek bütçe artışı'],
      ),
      FacilityTierInfo(
        tier: 4,
        name: 'Panoramik Şehir Manzaralı Sky Lounge',
        subtitle: 'Elit Sosyete',
        description: 'Stadyumun en üst katında Michelin standartlarında gurme mutfak ve lüks bar.',
        perkTitle: 'VIP Geliri & Sponsorluk Çarpanı',
        perkValue: '+₣12.000 / Hafta',
        highlights: ['Uluslararası zenginlerin ilgisi', 'Dev sponsorluk anlaşmaları', 'Kasa musluğu etkisi'],
      ),
      FacilityTierInfo(
        tier: 5,
        name: 'Hanedan Kraliyet Locası & Milyarderler Kulübü',
        subtitle: 'Zirvedeki Lüks',
        description: 'Özel helikopter pisti, altın kaplama süitler ve küresel elitlerin buluşma noktası.',
        perkTitle: 'VIP Geliri & Sponsorluk Çarpanı',
        perkValue: '+₣22.000 / Hafta',
        highlights: ['Maksimum haftalık zenginlik', 'Sonsuz sponsor desteği', 'Kulübe sınırsız finansal güç'],
      ),
    ],
  };

  static FacilityTierInfo getTierInfo(FacilityType type, int level) {
    final list = tiers[type] ?? [];
    final safeLevel = level.clamp(1, 5);
    return list.firstWhere(
      (t) => t.tier == safeLevel,
      orElse: () => list.isNotEmpty
          ? list.first
          : FacilityTierInfo(
              tier: safeLevel,
              name: '${type.label} Sv.$safeLevel',
              subtitle: 'Seviye $safeLevel',
              description: type.description,
              perkTitle: 'Kapasite & Güç',
              perkValue: '+%$safeLevel',
              highlights: ['Standart Tesis Özelliği'],
            ),
    );
  }
}
